apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
  - name: web-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  
  - name: content-updater
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo '<h1>Hello from Pod!</h1>' > /shared/index.html; sleep 60; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  
  volumes:
  - name: shared-data
    emptyDir: {}
